### ISSUE TITLE
User question about interpolation in true color imagery

### ISSUE THREAD

**Issue by kathys** [davidh-ssec/polar2grid#101]
Hi Dave,

I got an email from a p2g v1.2 tester who is concerned with something that looks like interpolation occurring in the output of her MODIS true color image.  There are a couple of stripes in the upper left of her data.  One shows a band of missing data through half of the image, surrounded by "blurring", and then below that is just another half stripe of just "blurring".  Can you tell us why this is happening?  Aniko says that this blurred stripe is missing data in the band 1 crefl file.   Please see her email below:

From: Anikó KERN <anikoc@nimbus.elte.hu>
Subject: Re: CSPP/IMAPP Polar2grid Beta software available to test
Date: August 21, 2014 at 3:37:19 AM CDT
To: Kathy Strabala <kathys@ssec.wisc.edu>

Dear Kathy,

Thank you for this new version of Polar2grid software. I have installed, and tried it with MODIS data even for an overpass with missing values caused by DSN. It works perfectly, thank you for it. I didn't try it with the test VIIRS data, should I?

I would have only one question, if you don't mind. I saw earlier as well a strange stripe in a few images, but not in every image. As I see it is present only in the crefl picture of Band 01, causing the stripe for the true color picture as well. If you are interested you can find these examples here: http://nimbus.elte.hu/~anikoc/kathy/
(I mean the stripe above the Norwegian Sea)
Have you experienced already any similar? Do you have any idea what can cause it? Is it just some visualization error? Sorry for my question :)

Cheers,
Aniko

**Comment by davidh-ssec** [comment]
Since I've rewritten fornav for this next v2.0 release, we should keep an eye out for a data set that shows this same problem and I'll try to diagnose what exactly is going on. I still believe that this is a "feature" of the EWA algorithm and that it will fill gaps in as best it can.
