### ISSUE TITLE
p2g v2.0 rc4 not producing fog geotiff at night

### ISSUE THREAD

**Issue by kathys** [davidh-ssec/polar2grid#107]
Night scene with this message appearing in p2g output text stream:

2015-05-19 16:34:29,019] : PID  14525 : INFO     : polar2grid.viirs.swath : create_ifog : Less than 10% of the data is at night, will not create 'ifog' product

Data on meelo: /data/users/kathys/night

or tarred up:  meelo:/data/users/kathys/NIGHT.tar.gz

**Comment by kathys** [comment]
Also true when trying to produce AWIPS fog product NetCDF file for this scene.  Tried 211e grid and received same message as above.

**Comment by davidh-ssec** [comment]
You will receive that message no matter what backend you use. That message is coming from the VIIRS frontend. When I get a chance I'll have to look at the actual calculation it's doing to determine night vs day.

**Comment by davidh-ssec** [comment]
@kathys I was going through github issues today and re-discovered this issue. We had something similar solved in #111, but I had only fixed it for reflectance products and not the fog products. So this will be fixed in the next v2.1rc tarball. We can talk about this more in our next meeting.
