### ISSUE TITLE
P2G v2.0 VIIRS --false-color option does not work

### ISSUE THREAD

**Issue by kathys** [davidh-ssec/polar2grid#108]
Used this command:

crefl2gtiff.sh --false-color -f $(cat CREFL_files.txt)

providing the software with a complete set of granules (all bands, all geo files) and it proceeded to create CREFL files first, and then ended without producing a final file.   The log contained this message.

INFO     : Running gridded scene through 'true_color' compositor
ERROR    : Missing 'green' band product, can not create rgb image
ERROR    : Could not properly modify scene using compositor 'true_color'

Looks like it produced the right individual crefl tifs but did not combine them to make an rgb.  This was the output tifs:

npp_viirs_viirs_crefl01_20150424_190954_wgs84_fit.tif
npp_viirs_viirs_crefl02_20150424_190954_wgs84_fit.tif
npp_viirs_viirs_crefl07_20150424_190954_wgs84_fit.tif
npp_viirs_viirs_crefl08_20150424_190954_wgs84_fit.tif

When I ran the command:  crefl2gtiff.sh --true-color -f $(cat CREFL_files.txt)
it worked just fine.

**Comment by davidh-ssec** [comment]
This should work:

    crefl2gtiff.sh false_color --false-color -f $(cat CREFL_files.txt)

Note the `false_color` added right after `crefl2gtiff.sh`.
