### ISSUE TITLE
Add capability to create VIIRS M-Band AWIPS-II NetCDF files

### ISSUE THREAD

**Issue by kathys** [davidh-ssec/polar2grid#109]
Our Alaska colleagues have requested the capability to produce VIIRS M-Band SDR images at 1km resolution for display in AWIPS-II.  Right now, I believe this capability only exists for the I-Bands and CREFL files.

**Comment by davidh-ssec** [comment]
Shouldn't be too hard. Version 2.0 I'm guessing?

**Comment by kathys** [comment]
Yes.

**Comment by davidh-ssec** [comment]
Does Jordan know about this request? Does he have channel names for these? Right now we use the wavelength for the I-band channels, but I'm guessing some of these might conflict with the M bands. And do they want all M-bands? If I can get a list of AWIPS II channel names for each M band that's desired then it's no problem.
