### ISSUE TITLE
P2G rc5 dynamic DNB data clippling?

### ISSUE THREAD

**Issue by kathys** [davidh-ssec/polar2grid#110]
I implemented the new P2G version rc5 on our operational data last night, and I noticed that the real earth viewer is still showing missing data over those nasty NaN regions.  My memory is not that great, but I thought the plan was to clip those values?

**Comment by davidh-ssec** [comment]
Yes this should have been fixed. I got an email from Teo in Italy that he's seeing some dimension issues too. I'll take a look.
