### ISSUE TITLE
MODIS crefl glue scripts incorrectly flagging %day of pass

### ISSUE THREAD

**Issue by kathys** [davidh-ssec/polar2grid#111]
I have a couple of MODIS passes from yesterday (18 UTC) that I am attempting to create true color images as well as AWIPS files from.  When using the P2G V2.0rc5 crefl2griff and crefl2awips glue scripts,  the software is failing on both with a message that says "Will not create modis crefl products because there is less than 10%% of day data".    These are both long day passes.  

I put the files I am using here:

ftp://ftp.ssec.wisc.edu/pub/ssec/kathys/aqua/
ftp://ftp.ssec.wisc.edu/pub/ssec/kathys/terra/

I did try out these glue scripts on our VIIRS data files, and it worked well.

**Comment by davidh-ssec** [comment]
If I remember right you had this problem with VIIRS like a month ago and I fixed it. Probably the same problem, but I forgot to fix it with MODIS. Will check it out.

**Comment by davidh-ssec** [comment]
Side question @kathys: Threshold for VIIRS day/night is set to solar zenith angle at 100, MODIS is 90. Is that fine with you or should they be the same?

**Comment by kathys** [comment]
Let's leave it this way.  I think they have different thresholds, like when the instrument changes from different DNB regimes.

**Comment by kathys** [comment]
Something new happened in P2G since previous releases.  I just tried the standard modis2awips glue script, and it did not create visible  band products for the aqua and terra passes either.  This has worked for a long time.

**Comment by davidh-ssec** [comment]
Yep, same function is used for CREFL and MODIS/VIIRS day checking (one for MODIS, one for VIIRS).
