### ISSUE TITLE
MODIS crefl2gtiff and crefl2awips not using 250m file to sharpen image

### ISSUE THREAD

**Issue by kathys** [davidh-ssec/polar2grid#113]
When I execute the crefl2gtiff.sh and crefl2awips.sh I noticed that the log message shows that the files are not sharpened.  

crefl2gtiff.sh false_color --false-color --true-color -f ../aqua/a1.15188.1830.{1000m,250m,geo}.hdf

Perhaps I am not executing it correctly.

Find the data that I used here:   ftp://ftp.ssec.wisc.edu/pub/ssec/kathys/p2g/

and the log file here:   ftp://ftp.ssec.wisc.edu/pub/ssec/kathys/p2g/

**Comment by davidh-ssec** [comment]
Could you check your log file location, I don't see any log files there.

**Comment by kathys** [comment]
Sorry:

ftp://ftp.ssec.wisc.edu/pub/ssec/kathys/crefl2gtiff_20150707_183000.log

**Comment by davidh-ssec** [comment]
Looks like the 250m file isn't properly being passed to the crefl program. Looking in to it...

**Comment by davidh-ssec** [comment]
Turns out this is because the MODIS corrected reflectance software now requires the 500m file in addition to the 1km and 250m, otherwise it fails. So closing this bug since its out of our hands for now.
