### ISSUE TITLE
not using any rescale configuration with the viirs2gtiff command

### ISSUE THREAD

**Issue by saragam25** [davidh-ssec/polar2grid#116]
hello, plz i am trying to use viirs2gtiff on viirs SDRs files and i don't want to use the any rescale configuration, i tried to use the command line --rescale-configs raw, but it didn't work

**Comment by davidh-ssec** [comment]
Hi Sara, I got your email about this issue too. Do you require the output to be geotiffs? Our last release of Polar2Grid doesn't support floats in geotiffs, but someone just asked about this before you. See #115 for details. In my last reply on that issue I go over how the user can edit the python code to add the functionality to get unscaled, 32-bit float geotiffs. If you are uncomfortable editing code then you will have to wait until the next release of Polar2Grid.
