### ISSUE TITLE
modis satellite zenith angle

### ISSUE THREAD

**Issue by eberndt** [davidh-ssec/polar2grid#117]
A request for MODIS satellite zenith angle be added to the MODIS frontend.  Here at SPoRT we added the following to modis_guidebook.py and modis_to_swath.py.  Can this be added to a future polar2grid release?

**File: modis_guidebook.py**
-Insert after line 92: K_SenZA = "senza_var"

-Insert after line 542:  K_SenZA: FileInfo("SensorZenith", offset_attr_name=None),

**File: modis_to_swath.py**
-Insert after line 233: PRODUCT_SenZA = "satellite_zenith_angle"

-Insert after line 305:  PRODUCTS.add_product(PRODUCT_SenZA, PAIR_1000M, "satellite_zenith_angle", guidebook.FT_GEO, guidebook.K_SenZA)

**Comment by davidh-ssec** [comment]
Thanks, I just added this information to the "develop" branch and this will be included in the next version of Polar2Grid. Thanks for the contribution. In the future feel free to do a GitHub Pull Request and I'll merge the code directly from your changes. Thanks again.

**Comment by eberndt** [comment]
Thanks for the quick response and accepting our contribution!  Next time we'll try the Pull Request.
