### ISSUE TITLE
Geolocation shift

### ISSUE THREAD

**Issue by spruceboy** [davidh-ssec/polar2grid#121]
I noticed some geo - location shifts in the geotiffs polar2grid is generating. 

I think polar2grid is using the the lower right corner of the pixel rather than the center. 
To test this, I generated a true color image at 300m resolution, and 3600m resolution for the same area, and if you compare them, there is a visible shift. I don't think there should be. 
![p2g_stock](https://cloud.githubusercontent.com/assets/243433/20116384/82f28826-a5a8-11e6-9434-dcd1f25e08a3.gif)
If you adjust corner locations in the geotiff by subtracting a half a pixel from the x values, and adding a half a pixel to the y values,  then there is no shift. 
![p2g_shift](https://cloud.githubusercontent.com/assets/243433/20116552/2456ff62-a5a9-11e6-8416-a01735966c35.gif)

If I remember right, ms2gt also did this - perhaps that is the source of the error? 

I generated these like: 
crefl2gtiff.sh --compress DEFLATE --grid-configs  ./viirs_geotiff_grids.grd -f ../npp.16306.2152/ -g alaska_tiny
crefl2gtiff.sh --compress DEFLATE --grid-configs  ./viirs_geotiff_grids.grd -f ../npp.16306.2152/ -g alaska_300

Where my grid file looks like this:
alaska_300,                 proj4, +proj=aea +lat_1=55 +lat_2=65 +lat_0=50 +lon_0=-154 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs, 12000, 12000, 300,-300,  -1502676.640, 3467676.360
alaska_tiny,                proj4, +proj=aea +lat_1=55 +lat_2=65 +lat_0=50 +lon_0=-154 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs, 1000, 1000, 3600,-3600,  -1502676.640, 3467676.360

**Comment by davidh-ssec** [comment]
Wow what a great example. Thanks Jay. This has me stumped. Ill have to go back in to the resampling code and see if I can figure this out. I am technically using the same fornav code as ms2gt but a new ll2cr that uses PROJ.4.

**Comment by davidh-ssec** [comment]
@spruceboy What are you using to view these images? I'm not sure the best viewer for comparing images of different resolutions. There are a lot of "black boxes" in the way.

**Comment by spruceboy** [comment]
@davidh-ssec  I used QGIS ( http://www.qgis.org - there are mac builds that are easy to install ), but it should be possible to replicate this with gdalwarp or gdal_translate (or any other gis tool ) to take two different resolutions and resample to the same scale.  Would you like an example using the command line tools?

**Comment by davidh-ssec** [comment]
I think I've got an example that I can test with. I'm using polar2grid and then just viewing the raw geotiff in Preview on Mac. The original grid you sent was large on my screen so I couldn't see the shift and it was difficult to zoom in and compare the images. I just shrunk the size of the grid so I can see the shift better.

**Comment by davidh-ssec** [comment]
Actually on second thought, a gdal command to do the half pixel shift would be nice.

**Comment by davidh-ssec** [comment]
@spruceboy Another thing, in QGIS when viewing these images at the same time do the left and top edges of the images perfectly line up or are they slightly misaligned?

My thought is that they should be slightly misaligned if the upper-left pixel of both images represents an area (one of 300m in width/height, one of 3600m) at location X, Y then the 3600m image should be 1650m larger all the way around the 300m image.

    300m pixel => 150m tall and wide
    3600m pixel => 1800m tall and wide
    # centered at the same location
    1800m - 150m = 1650m

**Comment by davidh-ssec** [comment]
@spruceboy I figured it out. The geotiff specification says that PixelIsArea geotiffs (what satellite imagery geotiffs are) expect coordinates to mean the upper-left corner of every pixel area. I have been assuming it to mean the center of the pixel since that is what satellite instrument data files do and like-wise that is what the EWA algorithm (ms2gt) uses too.

I will change the geotiff backend in P2G so that the geotransform of the geotiff adjusts the origin by a half pixel to represent this shift.

**Comment by spruceboy** [comment]
You can shift the tifs using the "-a_ullr" option to gdal_translate
```
gdal_translate -a_ullr -1502826.64 3467826.36 2097173.3600000003 -132173.64000000013 npp_viirs_true_color_20161101_215257_alaska_300.tif npp_viirs_true_color_20161101_215257_alaska_300.tif.shift.tif

gdal_translate -a_ullr -1504476.64 3469476.36 2095523.3600000003 -130523.64000000013 npp_viirs_true_color_20161101_215257_alaska_tiny.tif npp_viirs_true_color_20161101_215257_alaska_tiny.tif.shift.tif
```
You can compare them outside a gis client like qgis by cutting out an area to a fixed size, like so:

```
gdal_translate -projwin -703110.826 1954507.520 -387602.300 1670285.453 -outsize 716 645 npp_viirs_true_color_20161101_215257_alaska_300.shift.tif 300.tif
ggdal_translate -projwin -703110.826 1954507.520 -387602.300 1670285.453 -outsize 716 645 npp_viirs_true_color_20161101_215257_alaska_tiny.shift.tif tiny.tif
convert 300.tif tiny.tif  -loop 0 -set delay 100 -resize 80% true_color_compare.gif
```
hopefully this makes sense.

**Comment by spruceboy** [comment]
@davidh-ssec  👍 
Thanks for looking into it, shifting the geotransform put into the geotifs will work great!

**Comment by davidh-ssec** [comment]
@spruceboy if you are feeling adventurous you can try applying the above code change to your local version of P2G and see if it fixes it.

**Comment by spruceboy** [comment]
I am trying it now, thanks again!

**Comment by spruceboy** [comment]
Hmm, I am still seeing the issue, but perhaps I am building it wrong.  Let me double check..

**Comment by davidh-ssec** [comment]
Could you check the corner coordinates in the gdalinfo for each geotiff? They should be different now and before they were the same.

**Comment by spruceboy** [comment]
This is what I am seeing now:
![true_color_compare](https://cloud.githubusercontent.com/assets/243433/20192538/c2324d52-a736-11e6-9a4f-54770d644473.gif)

**Comment by davidh-ssec** [comment]
@spruceboy Ok I think I figured it out. Switch the shift in the Y direction from + to -.

**Comment by spruceboy** [comment]
![true_color_compare](https://cloud.githubusercontent.com/assets/243433/20194334/55301c7c-a73e-11e6-8c84-f08d8972a012.gif)

Is what I get using:
```
  def gdal_geotransform(self):
        # GDAL PixelIsArea (default) geotiffs expects coordinates for the
        # upper-left corner of the pixel
        # Polar2Grid and satellite imagery formats assume coordinates for
        # center of the pixel
        half_pixel_x = self['cell_width'] / 2.
        half_pixel_y = self['cell_height'] / 2.
        return self["origin_x"] - half_pixel_x, self["cell_width"], 0, self["origin_y"] - half_pixel_y, 0, self["cell_height"]
```

**Comment by davidh-ssec** [comment]
Awesome thanks for testing.
