### ISSUE TITLE
crefl2gtiff 

### ISSUE THREAD

**Issue by amal27** [davidh-ssec/polar2grid#122]
Hello, 
Can I use crefl2gtiff to create not rescaled gtiff images for all the bands

**Comment by davidh-ssec** [comment]
Hi, Creating an unscaled geotiff requires creating a float-type geotiff. This isn't possible in the last release we made of Polar2Grid (version 2.0), but it is discussed how to manually add it yourself in issue #115. We are also working on a new release of Polar2Grid that will include these changes soon.

However, if you just need unscaled data and if it doesn't need to be geotiff then you could use `glue.sh viirs binary ...` where the `...` are your normal set of parameters or if you need the corrected reflectances you could do `glue.sh crefl binary ...`. Hope this helps.

**Comment by amal27** [comment]
yes thank you, I used the option --dtype real4 to create unscaled geotiff, but I still need to create it for all the bands, for that, I tried the -p option, is that correct? is this option used to specify the bands we want to work with?

**Comment by davidh-ssec** [comment]
Yes the `-p` option should allow you to specify the bands you want. The `--list-products` flag should print out a list of the ones available and you can then pick which ones you want to specify to the `-p` flag.

**Comment by amal27** [comment]
Thank you for your help
