### ISSUE TITLE
VIIRS L1B rc6 visible band GeoTIFF images blank

### ISSUE THREAD

**Issue by kathys** [davidh-ssec/polar2grid#127]
Execution of polar2grid rc6 on VIIRS L1B files from 17 January 2017, 19:18 UTC resulted in blank geotiff image file creation for visible reflectance bands at both I and M band resolutions. Thermal bands images look fine, as well as DNB.  

All input, output and log files for this case can be found  at meelo:/data/users/kathys/viirs_l1b

**Comment by davidh-ssec** [comment]
I think I figured out the problem...the files changed again!

Previously reflectance channels had a `units` attribute that was set to `"none"` or at least `"1"`, but now that attribute doesn't exist at all. So P2G (actually satpy) doesn't know what units the data is in, so the rescaling thinks that it is getting reflectances in percents (what satpy produces), but actually it is getting reflectances in the range of 0-1. So the data is there, it just all gets flattened to one value.

The planned fix will be an update to satpy to force the units of the data in the file.
