### ISSUE TITLE
different results when implementing polar2grid.sh crefl gtiff and creflt2gtiff.sh

### ISSUE THREAD

**Issue by kathys** [davidh-ssec/polar2grid#129]
I was able to successfully execute this command:

crefl2gtiff.sh --false-color -f ../l1b/a1.17006.1855.{250m,500m,1000m,geo}.hdf

to create a MODIS false color image, but when I tried implementing it using the polar2grid.sh syntax:

polar2grid.sh crefl gtiff --false-color -f ../l1b/a1.17006.1855.{250m,500m,1000m,geo}.hdf

it failed.  Perhaps I do not have the syntax correct?  I put this example on 

meelo:/data/users/kathys/modis_gtiff

I also tried this:  polar2grid.sh crefl gtiff -f ../l1b/a1.17006.1855.{250m,500m,1000m,geo}.hdf

and it also failed.

**Comment by davidh-ssec** [comment]
What is the error message you are getting?

**Comment by kathys** [comment]
olar2grid.sh crefl gtiff --false-color -f ../l1b/a1.17006.1855.{250m,500m,1000m,geo}.hdf
INFO     : Initializing reader...
INFO     : Could not find any existing crefl output will use MODIS SDRs to create some
INFO     : Creating navigation product 'longitude_1000m'
INFO     : Creating navigation product 'latitude_1000m'
INFO     : Creating data product 'solar_zenith_angle'
ERROR    : Error running modis crefl
ERROR    : Could not create modis crefl files from SDRs
ERROR    : crefl frontend failed to load and sort data files (see log for details)
[viirs@dragon crefl]$ polar2grid.sh crefl gtiff  -f ../l1b/a1.17006.1855.{250m,500m,1000m,geo}.hdf
INFO     : Initializing reader...
INFO     : Could not find any existing crefl output will use MODIS SDRs to create some
INFO     : Creating navigation product 'longitude_1000m'
INFO     : Creating navigation product 'latitude_1000m'
INFO     : Creating data product 'solar_zenith_angle'
ERROR    : Could not create modis crefl files from SDRs
ERROR    : crefl frontend failed to load and sort data files (see log for details)

**Comment by kathys** [comment]
On the same data set, I am getting an error when implementing:

crefl2awips.sh --grid-coverage=0 -g 211e -f ../l1b/a1*.hdf

INFO     : Running gridded scene through 'crefl_sharpen' compositor
ERROR    : Could not sharpen products
ERROR    : Could not properly modify scene using compositor 'crefl_sharpen'
INFO     : Creating output from data mapped to grid 211e

polar2grid.sh crefl awips --grid-coverage=0 -g 211e -f ../l1b/a1*.hdf  

fails immediately with:

INFO     : Initializing reader...
INFO     : Could not find any existing crefl output will use MODIS SDRs to create some
INFO     : Creating navigation product 'longitude_1000m'
INFO     : Creating navigation product 'latitude_1000m'
INFO     : Creating data product 'solar_zenith_angle'
ERROR    : Error running modis crefl
ERROR    : Could not create modis crefl files from SDRs
ERROR    : crefl frontend failed to load and sort data files (see log for details)

Placed log at meelo:/data/users/kathys/modis_gtiff/log
