### ISSUE TITLE
MIRS btemp_90 problems for Metop-A 

### ISSUE THREAD

**Issue by kathys** [davidh-ssec/polar2grid#131]
Working on documenting MIRS products using rc6 release.  I am able to create all of the expected products, but the btemp_90 brightness temperatures do not look correct for Metop-A.

The output tif and log files (mirs2gtiff_20170206_160100.log) are here is here:
meelo:/data2/users/kathys/v2_1_testing/test_data/mirs/metopa

The command I use is:
polar2grid.sh mirs gtiff -p swe tpw sea_ice mirs_rain_rate mirs_btemp_90 -f ../input/IMG_SX.M2.D17037.S1601.E1607.B0000001.WE.HR.ORB.nc 

I ran the same command on Metop-B. and those BTs look good.

Might be a problem with the MIRS retrievals too.

Maybe I have metopa and b mixed up too.  M2 files should be Metop-A and M1 files are MetopB.  This appears to be switched for P2G.

**Comment by davidh-ssec** [comment]
As discussed in person, it seems the bad data is from MIRS. I did fix the M1/M2 issue though.
