### ISSUE TITLE
Cannot list files or create any VIIRS L1B reprojections using p2g rc7

### ISSUE THREAD

**Issue by kathys** [davidh-ssec/polar2grid#132]
I am going through some of my test cases with rc7.  I got to VIIRS L1B testing and I am no longer able to list out products or execute any writer with datasets that I had previously tested.  

meelo:/data2/users/kathys/v2_1_testing/test_data/viirs_l1b_day/l1b

meelo:/data2/users/kathys/v2_1_testing/test_data/viirs_l1b_day/gtiff1/viirs_l1b2gtiff_fail.log

polar2grid.sh viirs_l1b gtiff  --list-products -f ../l1b/*.nc
polar2grid.sh viirs_l1b gtiff  -f ../l1b/*.nc

**Comment by davidh-ssec** [comment]
This was due to a build bug. I was installing an old version of pyresample for some reason and this just happened to be the first time we ran in to this bug.
