### ISSUE TITLE
Clipping high values in netcdf files for AWIPS

### ISSUE THREAD

**Issue by spruceboy** [davidh-ssec/polar2grid#135]
Carl Dierking noticed that really high values in VIIRS data get clipped to "0" in the netcdf files polar2grid is generating for awips - that is really hot values in I04,M12, and M13 like which occur in wildfires,  are being set to 0.

Here is an example of the netcdf files vs the floating point geotiffs generated by p2g.  The Tifs are stretched from 270K to 360K, the netcdf files are just the pixel values in the netcdf files.   The purple/pink is no data. 

I04 netcdf
![i04](https://cloud.githubusercontent.com/assets/243433/25025980/f37c7502-2050-11e7-909a-76d15c73e965.png)

I04 GeoTiff
![i04 tif](https://cloud.githubusercontent.com/assets/243433/25025981/f3826b92-2050-11e7-890f-c8054388d023.png)

M13 netcdf
![m13](https://cloud.githubusercontent.com/assets/243433/25025987/fa9a6d94-2050-11e7-8b56-e67a102c29f7.png)

M13 GeoTiff
![m13 tif](https://cloud.githubusercontent.com/assets/243433/25025988/faad673c-2050-11e7-9890-1c86df34f918.png)

These images were generated outside awips, as it is bit harder to capture the direct comparison, but the same effect occurs in awips, and is of interest to us mainly because it makes things like fires really hard to see, as the high values get set to nodata, not the maximum valid data. 

I am not sure what is "correct" - perhaps this behavior is intended.  From my POV, it would be better if values larger than the maximum presentable in AWIPS are set to the maximum value, not nodata. 

Hopefully this makes sense! 
Thanks again for this awesome software!

**Comment by davidh-ssec** [comment]
@spruceboy Thanks for this issue. I've always hated the way we've scaled data for AWIPS. The default brightness temperature scaling we use in P2G is described here: http://www.ssec.wisc.edu/software/polar2grid/rescaling#brightness-temperature

In short, you are right the higher the temperature the lower the value in the NetCDF file (note the NetCDF file stores as signed bytes but AWIPS reads them as unsigned bytes...AWIPS). I was not very familiar with AWIPS when starting Polar2Grid so my understanding at the time was "do exactly what is already done otherwise your files won't show up in AWIPS". This is why 0 is used as a data value and the missing/fill value.

I'll bring this up with Kathy and Jordan and see what we can do.

**Comment by spruceboy** [comment]
Thanks for the link to the scaling and explaining the behavior.

To explain why this is of interest to folks - the awips users want to make rgb images in awips that highlight / show fires, like this: 
![natural_color_fire_awips](https://cloud.githubusercontent.com/assets/243433/25027697/2d03e33c-205b-11e7-951e-5ccd0ef8dcca.png)

And the way the values are "clipped" or "rolled" into 0 now mess that up - the "hot" areas of the fires all get set to nodata. 

Obviously this is not a major issue, we just wanted to bring it up.  Thanks again, we really appreciate your work!

**Comment by cfdierking** [comment]
Just discovered this problem occurring on other bands. Below is the 0.86 um channel...
![viirs_ 86um_170414_1401](https://cloud.githubusercontent.com/assets/13705629/25151785/6df263b8-2476-11e7-9835-b6f51222033e.png)

**Comment by kathys** [comment]
Carl,  We are working with Jordan to figure out a better way of scaling all of our AWIPS products.  Might not get to it until we arrive to work with you in Alaska.  If that timing does not work for you, please let me know, and we can bubble it up in priority.

Kathy

**Comment by spruceboy** [comment]
Dave, the test dataset that I used to make the examples above can be found here:
http://hippy.gina.alaska.edu/distro/fire_example.tar.gz
Please let me know if you need any additional test cases. 
The problem occurs in the fires in central Alaska. 
Thanks!
