### ISSUE TITLE
Strange values in floating point geotifs when in areas of no value data

### ISSUE THREAD

**Issue by spruceboy** [davidh-ssec/polar2grid#136]
We are seeing some funky values in some of the viirs bands in the "night" part of the data when the bands are not active. 

For example: 
![funky_values_2](https://cloud.githubusercontent.com/assets/243433/25973871/734d8ffc-3652-11e7-9799-563ba626aa38.jpeg)

![funky_values_example](https://cloud.githubusercontent.com/assets/243433/25973878/78117080-3652-11e7-98dd-700fe82fabde.jpeg)

The values seem to flip between nan and 0.  It isn't a huge deal, but a consistent value would be great. 

A sample/test dataset can be found here:
(rdrs) -> http://nrt-dds-prod.gina.alaska.edu/gilmore/snpp/level1/viirs/2017/05/NPP.20170511.121735.dat.gz/
(p2g) -> http://nrt-dds-prod.gina.alaska.edu/gilmore/snpp/geotiff_l1/viirs/2017/05/NPP.20170511.121735.dat.gz/

**Comment by davidh-ssec** [comment]
@spruceboy I've looked in to this and it looks like these `0`s are actually in the VIIRS SDR data. They don't have any fill values associated with them. So the values in the output file are technically correct and I don't think there is much I can do about it. If you think of something else, let me know.

**Comment by spruceboy** [comment]
Thanks for looking at it, bummer they are not set to a reasonable fill value.
