### ISSUE TITLE
AVHRR L1b reader doesn't handle big-endian data

### ISSUE THREAD

**Issue by howff** [davidh-ssec/polar2grid#140]
I have been creating L1b format big-endian for years because I thought that was how it's supposed to be.
polar2grid seems to handle only little-endian.
I've now modified my L1b writer to have a byte-swap option so the output can be fed into polar2grid.
However the document I used does explicitly say "Level 1b data sets generated and archived by NOAA are in Big Endian order"
Document "Advanced Very High Resolution Radiometer (AVHRR) Level 1b Format Differences, Version 1.1, September 27, 2004"

**Comment by davidh-ssec** [comment]
The code for reading AVHRR was copied from mpop back in the day. Now that we are moving to using SatPy for all internal functionality I would suggest creating an issue on https://github.com/pytroll/satpy or create a pull request with any changes that might be needed to accept the NOAA format. As it is now I don't think our AVHRR reader supports the NOAA format. I know you are familiar with PyTroll and SatPy so perhaps we can find a solution for you until a version of Polar2Grid is released that supports the NOAA format. However, none of our funding has pushed for NOAA AVHRR support so we can't make it a high priority. Of course, if SatPy supports it then future versions of Polar2Grid will support it.

**Comment by howff** [comment]
OK, thanks for your help.
