### ISSUE TITLE
Smashed pixels down the zero-degree meridian

### ISSUE THREAD

**Issue by howff** [davidh-ssec/polar2grid#142]
See this example from MODIS Terra

https://wetransfer.com/downloads/740141799d087524c0cb1ff23f6cbdd120180125124103/95f80442dd1b968b5a6ef49399de5ab920180125124103/0b1fcb

**Comment by howff** [comment]
Ah, I see a closed issue https://github.com/davidh-ssec/polar2grid/issues/139
which suggests using the develop branch.

**Comment by davidh-ssec** [comment]
Yes this has been fixed and will be included in version 2.2 (hopefully coming in the next couple business days).

**Comment by howff** [comment]
Tested version 2.2 and this issue is solved, thank you.
