### ISSUE TITLE
Custom output filename format

### ISSUE THREAD

**Issue by howff** [davidh-ssec/polar2grid#147]
I don't recall seeing a way of specifying a custom output filename format in the documentation.
Maybe most people are happy with the default so a command line option is not necessary.
However for those who prefer something different you can edit DEFAULT_OUTPUT_PATTERN in common/ShellB3/lib/python2.7/site-packages/polar2grid/gtiff_backend.py (for GeoTIFF output).
One suggestion, for those who prefer their products sorted by date, is:
"{grid_name}_{begin_time}_{instrument}_{product_name}_{satellite}.tif"
Since the name of the satellite which received the data is least useful it comes last not first.
For reference, the default is:
"{satellite}_{instrument}_{product_name}_{begin_time}_{grid_name}.tif"
Arguably {product_name} could come before {instrument} if different instruments shared the same products, for example truecolour.
Sorry, this is more like a user tip than a bug report.

**Comment by davidh-ssec** [comment]
@howff There is a `--output-pattern` command line flag for exactly this reason. No need to edit the source code.
