### ISSUE TITLE
NOAA 20 ID for ninjo backend

### ISSUE THREAD

**Issue by khunger** [davidh-ssec/polar2grid#148]
Hi,
got "9700014" as satellite ID for NOAA 20 for the ninjo backend.

**Comment by davidh-ssec** [comment]
Thanks @khunger. We should be able to include this in the next bug fix release of Polar2Grid. I added it  the following to the config: https://github.com/davidh-ssec/polar2grid/commit/915a783af35d9d225d35291e71c601924f6539d4#diff-5826a706c2f4dc45abe788e40eb8c274R4

If you have a chance to test it out locally by modifying your backend configuration file that would be great. Thanks.
