### ISSUE TITLE
Front end for CrIS SDR is desirable

### ISSUE THREAD

**Issue by rayg-ssec** [davidh-ssec/polar2grid#54]
It has been requested that quicklook (and optionally other ) band-slice BTs from CrIS SDR be supported by P2G. This is going into branch cris_rayg_201303 as a polar2grid.cris module.

**Comment by davidh-ssec** [comment]
As mentioned in #57 this code was left in a non-working state with the rest of polar2grid. As such the only copy of the CrIS tools are in the `hyperspectral` branch. I have not heard anything about a desire for these products besides the UW DR-RTV products.
