### ISSUE TITLE
Front end for Dual Regression EDR is desired

### ISSUE THREAD

**Issue by rayg-ssec** [davidh-ssec/polar2grid#55]
We've been asked to look at providing an HDF5 front end for dual regression retrievals for CrIS, Iasi, AIRS, etc. They share a similar format, though details may differ.

**Comment by davidh-ssec** [comment]
Wow, I really need to look at these more often. There is now a `polar2grid.drrtv` frontend package for this purpose. It is primarily used for future work by Nadia Smith.
