### ISSUE TITLE
resolve polar2grid.core.fbf vs keoni.fbf code forking

### ISSUE THREAD

**Issue by rayg-ssec** [davidh-ssec/polar2grid#58]
Low priority. 

The forking of the FBF module into polar2grid.core.fbf and keoni.fbf needs to be addressed in the long term, identifying which feature set belongs where ("classical" FBF object used by some code, versus Workspace semantics), and eradicating redundant implementations.

Include in this the possibility that both modules should be replaced with a promoted module ssec.format.fbf? 

Backward compatibility should be ensured by making the existing modules dependent on the common or surviving module. 

Eva and Nick should be consulted for their design opinion on how best to resolve this.

**Comment by davidh-ssec** [comment]
Polar2Grid v2.0 no longer uses the SSEC FBF filenaming scheme and instead names binary files as `product_name.dat` that are accompanied by a json file describing the dimensions and data type of the file (along with other p2g information).
