### ISSUE TITLE
"Same as" in metadata dictionary should just default instead of requiring copies?

### ISSUE THREAD

**Issue by rayg-ssec** [davidh-ssec/polar2grid#70]
Having the same value in 2-3 places in the metadata/band dictionary seems to be error-prone 27B-6 silliness. How about some nice defaults inherited from upstream scopes?

**Comment by davidh-ssec** [comment]
In v2.0 of polar2grid these "metadata dictionaries" have completely changed. They should be a little more sensible (although I'm sure they could be done better).
