### ISSUE TITLE
Add capability to create mapped image format output

### ISSUE THREAD

**Issue by kathys** [davidh-ssec/polar2grid#76]
This is an enhancement request for a future version that I did not want to forget about.  I would like to be able to create a .jpg (.png, or something like it), that includes a map overlay.  We get requests for things like a nice high resolution true color image to share with Dr. Goldberg or others.

**Comment by davidh-ssec** [comment]
This will be added in the next P2G release with an `add_coastlines.sh` script which calls the python `polar2grid.add_coastlines` script.
